name: CI for todolist-api

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: todolist-micro-services/pipeline/blob/master/server/unitTest.yml
