name: CI for todolist-api

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/trigger-workflow@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: todolist-micro-services/pipeline
          workflow: pipeline-workflow
          inputs: server/unitTest.yml
